#!/usr/bin/env bash
# Configures localhost and facebook.com to specific IPs
cp /etc/hosts /tmp/hosts
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' /tmp/hosts
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
cp /tmp/hosts /etc/hosts